apiVersion: v1
kind: Secret
metadata:
  name: copilot-secret
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.copilot.secrets.OPENAI_API_KEY | b64enc }}
  OAM_IP: {{ .Values.copilot.secrets.OAM_IP | b64enc }}
  WR_USER: {{ .Values.copilot.secrets.WR_USER | b64enc }}
  WR_PASSWORD: {{ .Values.copilot.secrets.WR_PASSWORD | b64enc }}
  TOKEN: {{ .Values.copilot.secrets.TOKEN | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.copilot.secrets.AWS_ACCESS_KEY_ID | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.copilot.secrets.AWS_SECRET_ACCESS_KEY | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.copilot.secrets.AWS_DEFAULT_REGION | b64enc }}
