apiVersion: v1
kind: Secret
metadata:
  name: copilot-secret
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.copilot.secrets.OPENAI_API_KEY | b64enc }}
  OAM_IP: {{ .Values.copilot.secrets.OAM_IP | b64enc }}
  WR_USER: {{ .Values.copilot.secrets.WR_USER | b64enc }}
  WR_PASSWORD: {{ .Values.copilot.secrets.WR_PASSWORD | b64enc }}
  TOKEN: {{ .Values.copilot.secrets.TOKEN | b64enc }}
