version: '3.7'
services:
  poc_genAI:
    image: <image_name>:<tag_name>
    container_name: stx-chatbot-be
    hostname: stx-chatbot-be
    restart: unless-stopped
    volumes:
      - /etc/kubernetes/pki/apiserver-kubelet-client.crt:/app/certs/apiserver-kubelet-client.crt
      - /etc/kubernetes/pki/apiserver-kubelet-client.key:/app/certs/apiserver-kubelet-client.key
      - /etc/kubernetes/pki/ca.crt:/app/certs/ca.crt
    environment:
      OPENAI_API_KEY: /run/secrets/openai_api_key
    ports:
      - 2000:2000

secrets:
  openai_api_key:
    file: openai_key.txt