version: '3.7'
services:
  poc_genAI:
    image: <image_name>:<tag_name>
    container_name: openstack-chatbot-be
    hostname: openstack-chatbot-be
    restart: unless-stopped
    network_mode: host
    environment:
      OPENAI_API_KEY: ${openai_key}
      OAM_IP: ${oam_ip}
      WR_USER: ${user}
      WR_PASSWORD: ${password}
      TOKEN: ${k8s_token}
      OS_IP: ${}
      OS_USER: ${}
      OS_PASSWORD: ${}
      OS_DOMAIN_NAME: ${}