version: '3.7'
services:
  poc_genAI:
    image: <image_name>:<tag_name>
    container_name: stx-chatbot-be
    hostname: stx-chatbot-be
    restart: unless-stopped
    network_mode: host
    volumes:
      - /etc/kubernetes/pki/apiserver-kubelet-client.crt:/app/certs/apiserver-kubelet-client.crt
      - /etc/kubernetes/pki/apiserver-kubelet-client.key:/app/certs/apiserver-kubelet-client.key
      - /etc/kubernetes/pki/ca.crt:/app/certs/ca.crt
    environment:
      OPENAI_API_KEY: ${openai_key}
      OAM_IP: ${oam_ip}